### ISSUE TITLE
启用停用无效

### ISSUE THREAD

**Issue by tanst** [bauw2008/luci-app-msd#1]
用的大雕（2022/12/12）的固件编译，已启用那个勾选了没什么反应

**Comment by bauw2008** [comment]
那是[lede]已经有[msd_lite]，现在这个是官方版本使用的。你可以选择[https://github.com/bauw2008/luci-app-msd/tree/2e842f071996a1247a26cdb2a2888dbb645bb89c](url)  这个版本luci。
